<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ConfigPage\**" />
    <EmbeddedResource Remove="ConfigPage\**" />
    <None Remove="ConfigPage\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Authen\AuthenModel.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="DynamicsReporting.Models.csproj.Backup.tmp" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.0" />
  </ItemGroup>

</Project>
